### PR TITLE
Remove old CEF ifdefs

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

Removes ifdefs that only benefit anyone using a CEF version older than 3770.
Since 3770 is the oldest version of CEF supported and shipped, their content was dead code.

This dead code got removed, none of the current functionality on any CEF >= 3770 should be effected.

### Motivation and Context

Stumbled across some of them while working on something else, and noticed they weren't needed.

### How Has This Been Tested?

Compiled on macOS.
This did require me to rebuild the cmake project and clear Xcode caches since Xcode has some scripts that assumed the removed header was still there, but that isn't project-related.

I unfortunately can't test Windows. 

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
As it stands, I'd personally prefer to make this change once we've actually moved away from 3770. Essentially, internally "support" one version below what's currently included, just in case things go haywire and we need to revert the CEF version for some reason.

**Comment by gxalpha** [comment]
Should I leave this PR open then and just wait?

**Comment by WizardCM** [comment]
Yep, leave it open and we'll review it closer to v28.

**Comment by pkviet** [comment]
Lgtm

**Comment by WizardCM** [comment]
After merging #323 this now has merge conflicts. Once they're solved, I'll merge this.

**Comment by WizardCM** [comment]
Ah, sorry I didn't catch this earlier - I would like to keep the `ENABLE_WASHIDDEN` option, as the goal (which I realise may not be realistic) is to eventually switch back to the previous behaviour.

**Pull request merged**
