### PR TITLE
Update ru-RU.ini

### PR DESCRIPTION
**Pull request by Blueberryy**
New translations

### CODE REVIEW

**Comment by dodgepong** [comment]
Localization is handled on our CrowdIn Project: https://crowdin.com/project/obs-studio

As such, we do not accept direct pull requests for localization updates.

**Comment by Blueberryy** [comment]
> Localization is handled on our CrowdIn Project: https://crowdin.com/project/obs-studio
> 
> As such, we do not accept direct pull requests for localization updates.

This text isn't exist on crowdin project for some reason

**Comment by dodgepong** [comment]
It does exist: https://crowdin.com/translate/obs-studio/148/en-ru?filter=advanced&value=12&sort_method=1&sort_ascending=0

**Comment by Blueberryy** [comment]
> It does exist: https://crowdin.com/translate/obs-studio/148/en-ru?filter=advanced&value=12&sort_method=1&sort_ascending=0

Ah nevermind then and thanks

**Pull request closed without merging**
