### PR TITLE
Enable Linux support

### PR DESCRIPTION
**Pull request by cg2121**
This requires CEF >= 3683

### CODE REVIEW

**Comment by cg2121** [comment]
To compile:

-grab the latest CEF for Linux at: http://opensource.spotify.com/cefbuilds/index.html
-unzip the folder
-cd into the folder
then
```
mkdir build && cd build
cmake -DCMAKE_CXX_FLAGS="-Wno-attributes"
make -j4
```

Change OBS cmake to:
```
cmake -DUNIX_STRUCTURE=1 -DCMAKE_INSTALL_PREFIX="/usr" -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="--- PATH TO CEF DIRECTORY ---" ..
```

**Comment by IainCole** [comment]
For reference in case anyone else tries this https://github.com/obsproject/obs-browser/pull/158

**Comment by ArisuOngaku** [comment]
> ```
> cmake -DUNIX_STRUCTURE=1 -DCMAKE_INSTALL_PREFIX="/usr" -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="--- PATH TO CEF DIRECTORY ---" ..
> ```

I had to `-DUNIX_STRUCTURE=0`, otherwise obs would segfault

**Comment by cg2121** [comment]
Linux support still needs some more work. I cant get the browser source to work when I install it to the system, but when I install it in portable mode it works just fine.

**Pull request closed without merging**
