### PR TITLE
Add "Copy page link" option to browser dock context menu

### PR DESCRIPTION
**Pull request by WizardCM**
### Description

Adds a "Copy page link" item to the context menu for browser docks.

image

### Motivation and Context

When using integrated YouTube chat, the URL changes per stream. Having an easy way to copy it is useful.

https://ideas.obsproject.com/posts/1924/add-copy-url-on-contextmenu-in-browser-dock

Additionally, the URL within a dock can change, through raids, navigation, etc. Having a way to get information about the current page can come in handy.

### How Has This Been Tested?

Right click in a browser dock.

### Types of changes
- Tweak (non-breaking change to improve existing functionality) 

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
@norihiro Yes, "page link" means the current URL. I'm open to alternatives. I didn't want to use "URL" as in "Copy page URL" as it feels too technical. Maybe "Copy page address"?

**Comment by Fenrirthviti** [comment]
"Address" is the commonly accepted verbiage I see many major browsers using to refer to things, and feels more correct to me.

**Comment by Fenrirthviti** [comment]
"Address" is the commonly accepted verbiage I see many major browsers using to refer to things, and feels more correct to me.

**Comment by norihiro** [comment]
I'd like to suggest "Copy current address"

A console web browser [w3m](https://w3m.sourceforge.net/)'s manual says "Show current address" to print the same information on the display.

**Comment by WizardCM** [comment]
Updated with "Copy current address" as the new wording.

**Pull request merged**
