### PR TITLE
obs-browser: Fix compiler warnings

### PR DESCRIPTION
**Pull request by cg2121**
### Description
This fixes warnings found with GCC on Linux.

### Motivation and Context
Warnings are annoying.

### How Has This Been Tested?
Compiled to see if warnings went away.

### Types of changes
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by gxalpha — CHANGES_REQUESTED** [review]
This is a bad idea, that switch is meant to fall through (otherwise, for example having `Full` access wouldn't give you access to `Advanced` and below).
However, this PR does prove RytoEX's point about the switch not being particularly beautiful. Feel free to refactor it.

**Comment by WizardCM** [comment]
Yeah my understanding was that this is intentional.

**Comment by RytoEX** [comment]
> 
> 
> This is a bad idea, that switch is meant to fall through (otherwise for example having `Full` access wouldn't give you access to `Advanced` and below). However, this PR does prove RytoEX's point about the switch not being particularly beautiful. Feel free to refactor it.

To avoid compiler warnings, wouldn't `[[fallthrough]]` be more appropriate?

**Comment by cg2121** [comment]
Updated it to use the [[fallthrough]] statements

**Pull request merged**
