### PR TITLE
Change product_version to user_agent_product

### PR DESCRIPTION
**Pull request by deviant**
### Description

Fixes compilation against CEF 91.1.0 and later. The `product_version` setting has been renamed to `user_agent_product`.

(Note: only merge this once you update the officially supported CEF to 91.1.0 (Chromium 91.0.4472.19) or later)

### Motivation and Context

Fixes a compilation failure. Here's the [CEF commit](https://bitbucket.org/chromiumembedded/cef/commits/02ae4597d8b6c895e46891a7596cf5fa1fe15df8) that caused this.

### How Has This Been Tested?

Built as part of OBS 27.0 using CEF 90.6.7 on NixOS (see https://github.com/NixOS/nixpkgs/pull/126505).

OBS starts up and displays the chosen web page when a Browser source is configured.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
This looks like a breaking change that isn't ifdef'd, and for a version of CEF we don't officially support.

**Comment by deviant** [comment]
I'm aware of both, hence you should consider this WIP until you bump the supported version.

**Comment by deviant** [comment]
(I'm happy to stick it behind an ifdef if you can give me a pointer to the right place to define this, FWIW)

**Comment by WizardCM** [comment]
Yep, please stick this behind compile conditional as there is no guarantee on when each platform will have the relevant CEF build configured.

```cpp
#if CHROME_VERSION_BUILD >= 4472
	CefString(&settings.user_agent_product) = prod_ver.str();
#else
	CefString(&settings.product_version) = prod_ver.str();
#endif
```

**Pull request merged**
