### PR TITLE
Enable Qt message loop on Linux

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Fixes https://github.com/obsproject/obs-studio/issues/7146 for normally *any* CEF build.

This fixes issues cause by building CEF with use_gtk=true which is the default.

### Motivation and Context

We built CEF with `use_gtk=false` to avoid having collision between Qt and CEF using the Glib event loop.
Using the Qt loop avoids this collision to ever happen.

### How Has This Been Tested?

Type (keyboard) in a custom browser dock, a crash should occur with `use_gtk=true` with no Qt loop.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by kkartaltepe** [comment]
thought we tried this and it didnt work to prevent gtk widgets from murdering cef.

**Comment by tytan652** [comment]
`use_gtk=false` was mainly added to fix https://github.com/obsproject/obs-studio/issues/7146 caused by CEF(/GTK) messing with Glib default loop which is used by Qt.

If this does not work in the long term, a MainMessageLoop (like MainMessageLoopMultithreadedGtk in cefclient) would need to be implemented to be sure that CEF does not use the GLib default context directly.

**Comment by RytoEX** [comment]
Is this change compatible with CEF 103/5060 as well as CEF 126+?

**Comment by tytan652** [comment]
Tested with https://cef-builds.spotifycdn.com/cef_binary_103.0.12%2Bg8eb56c7%2Bchromium-103.0.5060.134_linux64_minimal.tar.bz2 (so `use_gtk=true`)

And the keyboard crash does not occur, and look like it works.

**Review by WizardCM — APPROVED** [review]

**Review by RytoEX — APPROVED** [review]
Tentatively seems fine to me.

**Pull request merged**
